# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('historia', models.TextField()),
                ('descrip', models.CharField(max_length=150)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('imagen2', models.ImageField(blank=True, upload_to='')),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('url_video', models.CharField(default='null', max_length=255)),
                ('integrante_1', models.CharField(default='null', max_length=255)),
                ('integrante_2', models.CharField(default='null', max_length=255)),
                ('integrante_3', models.CharField(default='null', max_length=255)),
                ('integrante_4', models.CharField(default='null', max_length=255)),
                ('integrante_5', models.CharField(default='null', max_length=255)),
                ('nombre_facebook', models.CharField(default='null', max_length=255)),
                ('url_facebook', models.CharField(default='null', max_length=255)),
                ('nombre_twitter', models.CharField(default='null', max_length=255)),
                ('url_twitter', models.CharField(default='null', max_length=255)),
                ('nombre_youtube', models.CharField(default='null', max_length=255)),
                ('url_youtube', models.CharField(default='null', max_length=255)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tomnk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reseña', models.TextField(help_text='coloca una reseña de ti')),
                ('cargo', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
